[package]
name = "filecrawler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10"
data-encoding = "2.3.2"
walkdir = "2.3.2"
dpc-pariter = "0.5.1"